###################
## Configuration ##
###################

## Serveur ##
server:
    port: 8080

## Logging ##
logging:
    config: src/main/resources/logback.xml

## Spring ##
spring:
    main:
        show_banner: true

